name: ci
on:
  push:
  pull_request:

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dev tools
        run: python -m pip install ruff==0.5.7 black==24.8.0

      - name: Install project deps (if present)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Syntax smoke (no GUI)
        run: python -m compileall -q .
